import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import { PNG } from 'pngjs';
import { readFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { createDemoServer } from '../scripts/serve.js';

const server = createDemoServer();
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const base = `http://127.0.0.1:${server.address().port}`;
const browser = await chromium.launch({ ...(process.env.CONTRAST_BROWSER ? { channel: process.env.CONTRAST_BROWSER } : {}) });
const evidence = process.env.EVIDENCE_DIR || path.join(os.tmpdir(), 'contrast-evidence-task', 'demo');
await mkdir(evidence, { recursive: true });
let checks = 0;
const checked = label => { checks++; console.log(`✓ ${label}`); };
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  const errors = [], requests = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => requests.push(request.url()));
  await page.goto(`${base}/demo/`);
  await page.locator('#resultPanel:not([data-status="loading"])').waitFor();
  const defaultStatus = await page.locator('#resultPanel').getAttribute('data-status');
  const defaultRatio = await page.locator('#minimumRatio').textContent();
  assert.ok(['needs-review', 'quickcheck-clear'].includes(defaultStatus));
  await page.screenshot({ path: path.join(evidence, 'playground-desktop.png'), fullPage: true });
  checked('default photo produces a measured result');
  await page.locator('#scrim').fill('85');
  await page.locator('#resultPanel[data-status="quickcheck-clear"]').waitFor();
  checked('dark overlay produces a clear quickcheck');
  await page.locator('#resetButton').click();
  await page.waitForFunction(expected => document.querySelector('#minimumRatio').textContent === expected, defaultRatio);
  assert.equal(await page.locator('#resultPanel').getAttribute('data-status'), defaultStatus);
  assert.equal(await page.locator('#scrim').inputValue(), '12');
  checked('reset restores the original state');
  await page.locator('[data-background="gradient"]').click();
  await page.locator('#gradientStart').fill('#ffffff');
  await page.locator('#gradientEnd').fill('#ffffff');
  await page.locator('#scrim').fill('0');
  await page.locator('#foregroundHex').fill('#ffffff');
  await page.locator('#foregroundHex').press('Tab');
  await page.waitForFunction(() => document.querySelector('#minimumRatio').textContent.includes('1.00'));
  checked('white on white remains needs review');
  await page.locator('#foregroundHex').fill('#000000');
  await page.locator('#foregroundHex').press('Tab');
  await page.locator('#resultPanel[data-status="quickcheck-clear"]').waitFor();
  await page.waitForFunction(() => document.querySelector('#minimumRatio').textContent.includes('21.00'));
  checked('black on white matches the 21:1 reference');
  await page.locator('#fontWeight').selectOption('400');
  await page.locator('#fontSize').fill('14');
  await page.waitForFunction(() => document.querySelector('#thresholdLabel').textContent.includes('4.5'));
  checked('small regular text uses the normal-text threshold');
  await page.locator('#foregroundHex').fill('invalid');
  await page.locator('#foregroundHex').press('Tab');
  await page.locator('#resultPanel[data-status="unsupported"]').waitFor();
  assert.ok((await page.locator('#colorError').textContent()).trim().length);
  assert.equal(await page.locator('#exportJson').isEnabled(), false);
  checked('invalid input prevents a stale export');
  await page.locator('#foregroundHex').fill('#000000');
  await page.locator('#foregroundHex').press('Tab');
  await page.locator('#exportJson:enabled').waitFor();
  const hostile = '<img src=x onerror=alert(1)>';
  await page.locator('#sampleInput').fill(hostile);
  const [jsonDownload] = await Promise.all([page.waitForEvent('download'), page.locator('#exportJson').click()]);
  const exported = JSON.parse(await readFile(await jsonDownload.path(), 'utf8'));
  assert.ok(JSON.stringify(exported).includes(hostile));
  assert.ok(JSON.stringify(exported).includes('quickcheck-clear'));
  checked('JSON export retains the current text and result');
  const [htmlDownload] = await Promise.all([page.waitForEvent('download'), page.locator('#exportHtml').click()]);
  const html = await readFile(await htmlDownload.path(), 'utf8');
  assert.ok(!html.includes(hostile));
  assert.ok(html.includes('&lt;img'));
  const reportPage = await browser.newPage();
  await reportPage.setContent(html);
  assert.equal(await reportPage.locator('script').count(), 0);
  assert.ok(await reportPage.locator('img').count() >= 1);
  await reportPage.close();
  checked('visual export embeds evidence and escapes page text');
  await page.locator('#resetButton').click();
  const invalidFile = { name: 'invalid.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg/>') };
  await page.locator('#imageUpload').setInputFiles(invalidFile);
  assert.match(await page.locator('#uploadMessage').textContent(), /PNG|JPEG|WebP/);
  checked('unsupported upload is rejected with a useful message');
  const png = new PNG({ width: 40, height: 40 });
  png.data.fill(255);
  await page.locator('#imageUpload').setInputFiles({ name: 'test-white.png', mimeType: 'image/png', buffer: PNG.sync.write(png) });
  await page.waitForFunction(() => document.querySelector('#uploadMessage').textContent.includes('test-white.png'));
  await page.locator('#scrim').fill('0');
  await page.locator('#resultPanel[data-status="needs-review"]').waitFor();
  assert.equal(requests.filter(url => !url.startsWith(base) && !url.startsWith('data:') && !url.startsWith('blob:')).length, 0);
  checked('uploaded image is used locally without external requests');
  await page.locator('#resetButton').click();
  for (const width of [1440, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 1000 });
    await page.locator('#exportJson:enabled').waitFor();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.ok(await page.locator('#scrim').isVisible());
    await page.screenshot({ path: path.join(evidence, `playground-${width}.png`), fullPage: true });
    const accessibility = await new AxeBuilder({ page }).exclude('#stage').analyze();
    if (accessibility.violations.length) console.log(JSON.stringify(accessibility.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => ({ target: n.target, detail: n.failureSummary })) })), null, 2));
    assert.deepEqual(accessibility.violations.map(v => ({ id: v.id, count: v.nodes.length })), []);
    checked(`${width}px layout has no horizontal overflow and no axe UI violations (specimen excluded)`);
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator('#scrim').focus();
  const before = Number(await page.locator('#scrim').inputValue());
  await page.keyboard.press('ArrowRight');
  assert.equal(Number(await page.locator('#scrim').inputValue()), before + 1);
  checked('keyboard changes the overlay control');
  assert.deepEqual(errors, []);
  checked('no page JavaScript errors');
  console.log(`${checks} browser workflow checks passed. Screenshots: ${evidence}`);
} finally {
  await browser.close();
  await new Promise(resolve => server.close(resolve));
}
